### ISSUE TITLE
Point package.json main to existing file

### ISSUE THREAD

**Issue by LuudJanssen** [devshawn/react-dayjs#1]
The `main` property in `package.json` points to dist/index.js. However `dist/index.js` is not bundled on NPM, so if you install react-dayjs via NPM and try to load it, it fails. Either bundle `dist/index.js` or point `main` to `source/index.jsx`

**Comment by devshawn** [comment]
Whoops, I totally missed this when I released `v0.1.4`. Pushed `v0.1.5` with the fix. Sorry about that!
