### ISSUE TITLE
Upgrade to babel 7

### ISSUE THREAD

**Issue by devshawn** [devshawn/react-dayjs#2]
This currently uses babel 6 for building. It should be updated to use babel 7 and the newer babel plugins (that start with `@babel/...`) over the older versions.

This is a good first issue for someone who wants to give it a shot!

**Comment by ganesh-4212** [comment]
Hi @devshawn, I'm interested to work on this.

**Comment by devshawn** [comment]
Hi @ganesh-4212, go for it! Let me know if you have any questions. Details on how to run and build it can be [found here](https://github.com/devshawn/react-dayjs/blob/master/CONTRIBUTING.md). Though, you'll be changing the build process slightly in this. 😄
