### ISSUE TITLE
Could not resolve dependency with React @17.0.1

### ISSUE THREAD

**Issue by NikosMetaxakis** [devshawn/react-dayjs#31]
When trying to update the dayjs package with $npm update , the following message is produced from npm

$ npm update
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: client@0.1.0
npm ERR! Found: react@17.0.1
npm ERR! node_modules/react
npm ERR!   react@"^17.0.1" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^15.6.0 || ^16.0.0" from react-dayjs@0.2.1
npm ERR! node_modules/react-dayjs
npm ERR!   react-dayjs@"^0.2.1" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

this what $npm outdated produced

$ npm outdated
Package                                   Current  Wanted  Latest  Location                                                            Depended 
by
@testing-library/jest-dom       5.11.6       5.11.9    5.11.9   node_modules/@testing-library/jest-dom     client   
@testing-library/react            11.2.2       11.2.3   11.2.3     node_modules/@testing-library/react            client   
@testing-library/user-event   12.5.0       12.6.0   12.6.0     node_modules/@testing-library/user-event   client   
axios                                        0.21.0       0.21.1   0.21.1    node_modules/axios                                        client   
dayjs                                          1.9.7       1.10.3   1.10.3    node_modules/dayjs                                        client   
web-vitals                                  0.2.4         0.2.4     1.1.0    node_modules/web-vitals                                client   

something similar had happened more than a month ago when I was installing dayjs and initiating this project

**Comment by BryanDollery** [comment]
I had the same problem, but I couldn't wait for a fix from the author so I [rolled my own](https://github.com/BryanDollery/react-dayjs/tree/bryan). You can use it too if you're in a hurry. 

All I did is update the react packages and allowed range of react, upgrade the underlying libs with `npm upgrade`, and used `npm audit fix` to fix some vulnerabilities in the underlying dayjs package. I don't plan on changing anything else, and it's only a stop-gap until the author makes the relevant changes.

**Comment by NikosMetaxakis** [comment]
> I had the same problem, but I couldn't wait for a fix from the author so I [rolled my own](https://github.com/BryanDollery/react-dayjs/tree/bryan). You can use it too if you're in a hurry.
> 
> All I did is update the react packages and allowed range of react, upgrade the underlying libs with `npm upgrade`, and used `npm audit fix` to fix some vulnerabilities in the underlying dayjs package. I don't plan on changing anything else. It's only a stop-gap until the author makes the relevant changes, but it'll do the job while I'm waiting. YMMV

I switched to date-fns and created my own Component, thanks for sharing this temporary workaround

**Comment by devshawn** [comment]
This should be fixed in `0.3.2` :)
